export interface RelationshipChoiceOption {
  id: string;
  label: string;
  emotionTags?: string[];
  nextNodeId: string;
}

export interface RelationshipDialogueNode {
  id: string;
  act: number;
  type: "dialogue";
  lines: string[];
  nextNodeId: string | null;
}

export interface RelationshipChoiceNode {
  id: string;
  act: number;
  type: "choice";
  choices: RelationshipChoiceOption[];
}

export interface RelationshipEndingNode {
  id: string;
  act: number;
  type: "ending";
  lines: string[];
}

export type RelationshipEventNode =
  | RelationshipDialogueNode
  | RelationshipChoiceNode
  | RelationshipEndingNode;

export interface RelationshipEventScript {
  totalActs: number;
  startNodeId: string;
  nodes: RelationshipEventNode[];
}

export interface RelationshipEventSeed {
  id: string;
  characterId: string;
  title: string;
  description: string;
  coverImageUrl: string;
  requiredIntimacy: number;
  prerequisiteEventIds: string[];
  summary: string;
  cgPrompt: string;
  cgImageUrl: string;
  sortOrder: number;
  script: RelationshipEventScript;
}

function dialogue(id: string, act: number, lines: string[], nextNodeId: string | null): RelationshipDialogueNode {
  return { id, act, type: "dialogue", lines, nextNodeId };
}

function choice(id: string, act: number, choices: RelationshipChoiceOption[]): RelationshipChoiceNode {
  return { id, act, type: "choice", choices };
}

function ending(id: string, act: number, lines: string[]): RelationshipEndingNode {
  return { id, act, type: "ending", lines };
}

export const RELATIONSHIP_EVENT_SEEDS: RelationshipEventSeed[] = [
  {
    id: "lintang_300",
    characterId: "preset_lintang",
    title: "雨里的纸箱小猫",
    description: "雨天便利店屋檐下，她第一次愿意把狼狈留给你看。",
    coverImageUrl: "/events/lintang_300_cg.png",
    requiredIntimacy: 300,
    prerequisiteEventIds: [],
    summary:
      "那天雨下得很大，林棠抱着湿掉的纸箱和一只小猫，在屋檐下嘴硬地说自己没事。你替她挡住了雨，也陪她把小猫安顿好、把狼狈一点点收起来。她没有明说依赖，但已经开始把你当成可以安心站在身边的人。",
    cgPrompt:
      "日系 GalGame 剧情插画，雨天便利店屋檐下，暖黄灯光与冷蓝雨幕对比，林棠抱着纸箱和小猫，湿发贴在脸侧，手里拿着半湿的速写本，男主在旁边撑伞，背景有便利店灯牌、积水路面和远处车灯，氛围温暖治愈，清爽配色，细腻表情，轻微雨丝，视觉小说封面感，高清",
    cgImageUrl: "/events/lintang_300_cg.png",
    sortOrder: 1,
    script: {
      totalActs: 5,
      startNodeId: "lintang_300_act1",
      nodes: [
        dialogue("lintang_300_act1", 1, [
          "（傍晚的雨毫无预兆地砸下来，便利店的屋檐太窄，雨帘几乎贴着脚尖往下泼，空气里全是被打湿的沥青和泥土混在一起的潮气。）",
          "哎？你怎么也在这里啊……你也没带伞？",
          "（林棠抱着一个已经被雨水泡得发软的纸箱，碎花裙摆贴在膝盖上，刘海湿了一半黏在额头，却还在努力用手肘把纸箱护住。）",
          "别、别靠太近啦，风从那边来，你站过来会被淋到的。",
          "……不是我要在这里罚站，是这个小家伙不肯出来。",
          "（纸箱里传来一声细细的、像是在发抖的猫叫，一团脏兮兮的橘色毛球正把自己缩成最小的形状，鼻尖湿漉漉的。）",
          "我回来的路上看到它蹲在垃圾桶旁边淋雨，就……反正你别笑我。",
          "它一看到我就不走了，我总不能把它丢在那里吧。",
          "（她低头看了一眼纸箱里的小猫，嘴角没忍住弯了一下，又赶紧抿回去，像是怕被你发现她其实心软得不行。）",
        ], "lintang_300_choice1"),
        choice("lintang_300_choice1", 1, [
          { id: "umbrella", label: "把伞撑过去给她", emotionTags: ["守护"], nextNodeId: "lintang_300_act2" },
          { id: "shield", label: "站到她外侧挡风", emotionTags: ["陪伴"], nextNodeId: "lintang_300_act2" },
          { id: "ask_cat", label: "蹲下来看小猫", emotionTags: ["温柔"], nextNodeId: "lintang_300_act2" },
          { id: "take_box", label: "先帮她接过纸箱", emotionTags: ["行动力"], nextNodeId: "lintang_300_act2" },
        ]),
        dialogue("lintang_300_act2", 2, [
          "（雨点顺着伞骨一颗一颗砸进地面的积水里，便利店门口的自动门开了又关，暖光一闪一闪地扫过她微微发红的鼻尖和被雨打湿的睫毛。）",
          "它刚才一直缩在箱子角落，看到我伸手就往后退，后来我蹲了好久它才肯让我碰。",
          "你知道吗，小猫刚被淋湿的时候整个身体都在抖，但它还是会努力把自己团起来……",
          "（她说着低头看了一眼纸箱，声音突然小了，像是在说小猫又像是在说别的什么。）",
          "我的画稿也被淋到了一点……不过没关系，回去吹干就好。",
          "那个……你要是赶时间的话，不用陪我，我自己能搞定的。",
          "（她这么说着，手指却不自觉地攥紧了纸箱边缘，指节发白，雨声大到几乎要把她的声音吞掉。）",
          "真的，我经常一个人处理这种事。",
          "……好吧，你不走的话，那就先站一会儿。",
        ], "lintang_300_choice2"),
        choice("lintang_300_choice2", 2, [
          { id: "carry_box", label: "纸箱给我抱", emotionTags: ["可靠"], nextNodeId: "lintang_300_act3" },
          { id: "dont_force", label: "别硬撑了", emotionTags: ["关心"], nextNodeId: "lintang_300_act3" },
          { id: "send_together", label: "一起想办法安置它", emotionTags: ["行动力"], nextNodeId: "lintang_300_act3" },
          { id: "buy_towel", label: "我去买条毛巾先擦擦", emotionTags: ["细心"], nextNodeId: "lintang_300_act3" },
        ]),
        dialogue("lintang_300_act3", 3, [
          "（你们一起蹲下来的时候，小猫终于从纸箱角落探出脑袋，先是怯怯地叫了一声，然后歪歪扭扭地爬到林棠掌心里，把整张湿漉漉的小脸埋进她的手指缝。）",
          "你看……它居然不怕你。小猫一般对陌生人很凶的。",
          "（林棠的眼眶突然红了一下，她赶紧偏过头，假装在看路口的红绿灯，但声音已经带上了一点不太稳的颤。）",
          "……其实，我有点高兴你在这里。",
          "不是因为猫啦，是因为……我今天本来觉得，一个人淋着雨抱着这个破箱子回去，会特别狼狈。",
          "你别笑啊，我就是……今天有点想撒娇。",
          "（她说完立刻把脸别开，耳尖已经红透了，手指无意识地顺着小猫的背轻轻抚过去。）",
          "我的合租屋不让养宠物，我连带它回家都做不到，我都不知道自己在坚持什么……",
          "但是你来了，我好像就没那么慌了。",
        ], "lintang_300_choice3"),
        choice("lintang_300_choice3", 3, [
          { id: "depend", label: "你可以多依赖我一点", emotionTags: ["安心"], nextNodeId: "lintang_300_act4" },
          { id: "my_place", label: "先带去我那里", emotionTags: ["行动力"], nextNodeId: "lintang_300_act4" },
          { id: "buy_drink", label: "先给你买杯热的", emotionTags: ["照顾"], nextNodeId: "lintang_300_act4" },
          { id: "not_clumsy", label: "你一点都不狼狈", emotionTags: ["温柔"], nextNodeId: "lintang_300_act4" },
        ]),
        dialogue("lintang_300_act4", 4, [
          "（雨声在头顶连成一整片白噪音，便利店门口的人流来来往往，没人注意到屋檐下蹲着的两个人和一只橘色小猫，像是一小块被世界暂时忘记的角落。）",
          "那……你真的不嫌麻烦吗？",
          "我不是要你负责什么，就是……我想确认，自己不会又把事情搞砸。",
          "（她把小猫轻轻托起来，它打了一个小小的喷嚏，然后乖乖窝进她的围巾里，闭上了眼睛。）",
          "你看，它信你了。猫是很敏感的，它不会随便在人面前睡着。",
          "还有，今天的画稿虽然湿了，但我好像也没那么难过了。",
          "因为你在嘛。",
          "（她说出这句话的时候声音很轻，像是自己也被这份坦诚吓到了一点，手指微微收紧了围巾的边角。）",
          "所以……你以后如果看到我在逞强，就直接走到我身边来，别等我开口。",
          "因为我可能不会说，但我其实……很需要。",
        ], "lintang_300_choice4"),
        choice("lintang_300_choice4", 4, [
          { id: "of_course", label: "好，我记住了", emotionTags: ["耐心"], nextNodeId: "lintang_300_act5" },
          { id: "ill_stay", label: "我陪你把它安顿好", emotionTags: ["陪伴"], nextNodeId: "lintang_300_act5" },
          { id: "you_can_lean", label: "以后靠着我就好", emotionTags: ["温柔"], nextNodeId: "lintang_300_act5" },
          { id: "next_time", label: "下次换我先找到你", emotionTags: ["守护"], nextNodeId: "lintang_300_act5" },
        ]),
        dialogue("lintang_300_act5", 5, [
          "（雨势终于小了一点，便利店的灯牌在积水里拉出一道长长的暖黄色倒影，空气里的潮气开始变得温柔，像是整个傍晚都松了一口气。）",
          "嗯……那我们走吧。雨小了。",
          "（林棠站起来的时候有点晃，你下意识扶了她一把，她的手指很凉，却在碰到你的瞬间轻轻握了一下。）",
          "我会把它照顾好的。虽然还不知道怎么瞒过房东，但是……会想到办法的。",
          "不是只记住小猫喔，是记住你今天替我接住狼狈的样子。",
          "你是第一个让我觉得，落汤鸡的时候也可以不用躲起来的人。",
          "（她抱着裹在围巾里的小猫走进雨里，回头看了你一眼，笑得有点不好意思。）",
          "如果以后我又嘴硬说我没事……你就像今天一样，直接站过来就好了。",
          "谢谢你。今天真的，谢谢。",
        ], "lintang_300_choice5"),
        choice("lintang_300_choice5", 5, [
          { id: "always_here", label: "我会一直来找你的", emotionTags: ["陪伴"], nextNodeId: "lintang_300_end" },
          { id: "share_weather", label: "以后下雨都一起走", emotionTags: ["同行"], nextNodeId: "lintang_300_end" },
          { id: "promise_cat", label: "帮你一起想养猫的办法", emotionTags: ["温柔"], nextNodeId: "lintang_300_end" },
          { id: "open_umbrella", label: "下次我先替你撑伞", emotionTags: ["守护"], nextNodeId: "lintang_300_end" },
        ]),
        ending("lintang_300_end", 5, [
          "那天的雨最终停在了入夜之前，林棠把被淋湿的速写本仔细夹进文件袋，又从里面抽出一张画着橘猫的草图悄悄塞进你手里。",
          "她红着耳尖小声说了一句：「下次下雨，你要第一个来找我喔。」",
          "一只流浪的小猫被接住了，而一段关系也在那个屋檐下，悄悄长出了第一根柔软的根。",
        ]),
      ],
    },
  },
  {
    id: "lintang_600",
    characterId: "preset_lintang",
    title: "改稿夜的双人灯",
    description: "深夜工作室的暖黄灯下，她开始习惯和你并肩解决难题。",
    coverImageUrl: "/events/lintang_600_cg.png",
    requiredIntimacy: 600,
    prerequisiteEventIds: ["lintang_300"],
    summary:
      "那一夜，林棠把自己最不想示弱的样子也给了你看。你没有替她做决定，只是陪她把卡住的地方一点点拆开、重拼好。她开始相信，有些难题不是一个人扛的，有你在的时候，她可以不用那么逞强。",
    cgPrompt:
      "日系视觉小说插画，深夜插画工作室，暖黄台灯照着杂乱的草稿、色卡、便签和两只马克杯，林棠趴在桌边，表情疲惫又嘴硬，男主在旁边帮她整理打印纸，窗外是安静的城市夜景，背景有电脑显示屏、未画完的分镜稿和散开的胶带，氛围亲密克制、青春治愈、细腻光影、高清",
    cgImageUrl: "/events/lintang_600_cg.png",
    sortOrder: 2,
    script: {
      totalActs: 5,
      startNodeId: "lintang_600_act1",
      nodes: [
        dialogue("lintang_600_act1", 1, [
          "（深夜十一点的插画工作室只亮着一盏台灯，窗外整条街已经安静下来，偶尔有出租车的尾灯从窗帘缝里划过去，空气里弥漫着冷掉的速溶咖啡和铅笔屑混在一起的味道。）",
          "你怎么来了啊……我没说让你来吧？",
          "（她的语气想装得漫不经心，但声音哑得根本藏不住，桌面上散着七八张被揉皱又展平的草稿，电脑屏幕上的画面停在一个涂了又删的色块上。）",
          "别看我这样，我只是稍微、稍微有一点卡住。",
          "没有哭啊！谁哭了！我就是改到第七版了甲方又说要推翻重来……",
          "（她用手背快速蹭了一下眼角，假装是困的，但鼻头已经红了。）",
          "你要是来笑话我的就赶紧回去，我今天没心情跟你拌嘴。",
          "……好吧，既然来都来了，那你就坐这儿吧。别碍事就行。",
        ], "lintang_600_choice1"),
        choice("lintang_600_choice1", 1, [
          { id: "stay_with_you", label: "我陪你改", emotionTags: ["并肩"], nextNodeId: "lintang_600_act2" },
          { id: "drink_first", label: "先给你倒杯热水", emotionTags: ["照顾"], nextNodeId: "lintang_600_act2" },
          { id: "slow_down", label: "先停一停", emotionTags: ["安抚"], nextNodeId: "lintang_600_act2" },
          { id: "split_task", label: "你说思路，我帮你整理", emotionTags: ["分工"], nextNodeId: "lintang_600_act2" },
        ]),
        dialogue("lintang_600_act2", 2, [
          "（你给她倒了热水，把散落在桌面上的色卡按色系重新码好，她一直盯着屏幕没动，但你注意到她的肩膀在微微发抖，不知道是冷还是气的。）",
          "……其实我白天就已经改不动了。一直坐在这里觉得自己特别没用。",
          "甲方说我的用色太「学生气」，让我改成更有「商业感」的。可是我都不知道「商业感」是什么东西……",
          "（她终于把笔扔在桌上，整个人往椅背上靠过去，天花板的灯管在她眼睛里映出一小块冷白色的光。）",
          "我刚才其实有一点想哭，但你来了就没那么想了。",
          "不是因为你有多厉害啦……就是，有个人在旁边坐着，我就不会觉得这间屋子要把我吞掉。",
          "你别这样看我，我没有在撒娇！",
          "（她说着把脸别开，但嘴角已经在抖了，手指无意识地转着那支被咬出牙印的自动铅笔。）",
          "……好吧，我承认我有一点点、一丁点在撒娇。你管不着。",
        ], "lintang_600_choice2"),
        choice("lintang_600_choice2", 2, [
          { id: "be_honest", label: "想哭就哭吧", emotionTags: ["坦诚"], nextNodeId: "lintang_600_act3" },
          { id: "organize", label: "我来帮你理草稿", emotionTags: ["可靠"], nextNodeId: "lintang_600_act3" },
          { id: "lean_on_me", label: "靠我肩膀歇一会儿", emotionTags: ["亲近"], nextNodeId: "lintang_600_act3" },
          { id: "take_break", label: "先去阳台吹吹风", emotionTags: ["缓冲"], nextNodeId: "lintang_600_act3" },
        ]),
        dialogue("lintang_600_act3", 3, [
          "（你们把所有草稿摊开在地板上，一张一张地看过去，把甲方的修改意见拆成具体的问题——配色、构图、字体、留白——然后逐个攻破。林棠一开始还嘴硬说「我自己来」，但手已经在跟着你的思路动了。）",
          "等等……你刚才说的那个方向……好像可以。",
          "（她从地上捞起一张之前被揉掉的草稿，眼睛突然亮了，像是在一堆碎片里终于拼出了完整的拼图。）",
          "如果把这个配色方案和第三版的构图组合起来……好像真的能行？",
          "你怎么想到的！我在这里卡了六个小时都没发现这个角度！",
          "（她说着已经扑回电脑前开始调色了，手指在数位板上飞快地划过，脸上的表情从疲惫变成了专注，眉心那道皱纹终于松开了。）",
          "你说我很厉害？……哼，这句夸奖我收了。",
          "不过，如果没有你帮我把思路拆开，我大概会一直钻在死胡同里出不来。",
          "以后如果我又卡住了……你也要像今天这样，来把我从乱掉的地方拎出来喔。",
        ], "lintang_600_choice3"),
        choice("lintang_600_choice3", 3, [
          { id: "of_course", label: "随时来找我", emotionTags: ["回应"], nextNodeId: "lintang_600_act4" },
          { id: "mutual_help", label: "你也会替我想办法的", emotionTags: ["默契"], nextNodeId: "lintang_600_act4" },
          { id: "accept_need", label: "那我收下你的信任", emotionTags: ["信任"], nextNodeId: "lintang_600_act4" },
          { id: "keep_together", label: "以后难关一起过", emotionTags: ["并肩"], nextNodeId: "lintang_600_act4" },
        ]),
        dialogue("lintang_600_act4", 4, [
          "（最终版的画面终于在屏幕上成形了，林棠把椅子往后推了一点，整个人像是从水底浮上来一样长长地呼了一口气。窗外的天际线已经泛起一层很浅很浅的蓝，不知不觉坐了一整夜。）",
          "……做完了。",
          "（她盯着屏幕看了几秒，然后突然转过来看你，眼圈红红的，但笑得很真。）",
          "我其实知道自己在硬撑。每次遇到难题我都会把所有人推出去，觉得自己一个人扛才算本事。",
          "可是你来了以后，我突然觉得，狼狈也没有那么可怕。",
          "因为你不会笑我画得不好，也不会嫌我烦……你只会把我拉回正轨。",
          "（她低头拨弄着被画得满是痕迹的数位板笔，声音变得很小很小。）",
          "我以前总觉得，只有把一切都做对了，才配被人夸一句「厉害」。",
          "可你刚才没有只看结果，你看的是……我撑了多久。",
          "所以，谢谢你。下一次我会更早告诉你，我其实需要你。不会再一个人硬扛了。",
        ], "lintang_600_choice4"),
        choice("lintang_600_choice4", 4, [
          { id: "laugh_no", label: "我永远不会笑你", emotionTags: ["温柔"], nextNodeId: "lintang_600_act5" },
          { id: "together_next", label: "下次还一起熬夜改稿", emotionTags: ["约定"], nextNodeId: "lintang_600_act5" },
          { id: "rest_first", label: "先趴一会儿吧", emotionTags: ["照顾"], nextNodeId: "lintang_600_act5" },
          { id: "trust_me", label: "把乱掉的部分都给我就好", emotionTags: ["信任"], nextNodeId: "lintang_600_act5" },
        ]),
        dialogue("lintang_600_act5", 5, [
          "（台灯还亮着，但屋子里的气氛已经完全变了，不再是刚才那种赶工时的紧绷和焦虑，而是像被什么柔软的东西填满了，连空气都暖洋洋的。）",
          "你知道吗，我以前画画从来不让别人看过程，只让别人看成品。",
          "因为过程太丑了……又涂又改又揉掉，跟我本人一样狼狈。",
          "（她把脸埋进臂弯里，声音闷闷的，但你能听出她在笑。）",
          "可是今天你看到了全部。最丑的草稿、最笨的错误、最爱逞强的样子……全都被你看到了。",
          "结果你还是坐在这里，哪都没去。",
          "那以后……如果我又想逞强，你就直接推门进来好了。",
          "不用敲门，不用问我「要不要帮忙」，直接进来，坐在这把椅子上。",
          "（她从臂弯里抬起头，看着你的时候眼睛亮得像装了一整个台灯的光。）",
          "因为有你在的时候，我可以不用那么逞强了。这是真的。",
        ], "lintang_600_choice5"),
        choice("lintang_600_choice5", 5, [
          { id: "need_me", label: "那就更早告诉我", emotionTags: ["坦诚"], nextNodeId: "lintang_600_end" },
          { id: "watch_you", label: "我会一直看着你的", emotionTags: ["陪伴"], nextNodeId: "lintang_600_end" },
          { id: "share_rhythm", label: "以后一起调整节奏", emotionTags: ["默契"], nextNodeId: "lintang_600_end" },
          { id: "make_space", label: "这把椅子我包了", emotionTags: ["温柔"], nextNodeId: "lintang_600_end" },
        ]),
        ending("lintang_600_end", 5, [
          "天快亮的时候，林棠把最终版的插画存好，从桌角翻出一张便签纸，歪歪扭扭地画了两个火柴人并肩坐在台灯下，写了一行字：「共同作战成功！」然后红着脸塞进你手心。",
          "她嘟囔着说只是顺手画的，但最后还是没忍住补了一句：「以后如果我又卡住了，你别嫌我烦。你来，我就会好起来的。」",
        ]),
      ],
    },
  },
  {
    id: "lintang_900",
    characterId: "preset_lintang",
    title: "把未来画成同一页",
    description: "她终于把那句绕着说的话，认真留给了你。",
    coverImageUrl: "/events/lintang_900_cg.png",
    requiredIntimacy: 900,
    prerequisiteEventIds: ["lintang_300", "lintang_600"],
    summary:
      "林棠在夜里把那句一直绕着说的话，轻轻放到了你面前：她不只想和你停在眼前这一刻，她想把你带进自己的未来。你没有让她一个人面对答案，而是把回应留在了同一页里，和她一起往前翻。",
    cgPrompt:
      "日系 GalGame 高潮剧情插画，毕业展后夜晚的城市屋顶或高处平台，远处灯火通明，林棠手里拿着折好的草稿纸和手帐，表情认真又微微脸红，男主站在她对面，背景有风吹动的纸片、城市霓虹和未完成的展板，气氛安静、克制、带一点告白感，视觉小说终章封面感，浪漫但清爽，高清细腻",
    cgImageUrl: "/events/lintang_900_cg.png",
    sortOrder: 3,
    script: {
      totalActs: 5,
      startNodeId: "lintang_900_act1",
      nodes: [
        dialogue("lintang_900_act1", 1, [
          "（毕业展结束后的天台上只剩下风声和远处断断续续的车流，城市的灯火铺成一片暖黄色的海，楼下展厅的灯已经全灭了，只有楼梯间的应急灯还亮着一点橘色的光。）",
          "你怎么真的上来了啊……我还以为你会先去吃散伙饭。",
          "（林棠靠在天台的围栏边，手里攥着一张被风吹得有点皱的纸，头发被夜风吹得乱七八糟，裙角不停地翻，但她一直没松手。）",
          "别问我为什么叫你来这里……我就是想把今晚的尾巴留得久一点。",
          "展览结束了，大家都散了，我突然觉得特别空。",
          "不是难过那种空，是像画完一整本速写本、翻到最后一页的那种空。",
          "（她看着远处的灯火出了一会儿神，然后转过来看你，眼睛被城市的光映得亮亮的。）",
          "如果你现在下楼，我会有点不甘心的。真的。",
          "你……可以再陪我站一会儿吗？",
        ], "lintang_900_choice1"),
        choice("lintang_900_choice1", 1, [
          { id: "stay_longer", label: "想站多久都行", emotionTags: ["停留"], nextNodeId: "lintang_900_act2" },
          { id: "say_it", label: "你有话想跟我说？", emotionTags: ["倾听"], nextNodeId: "lintang_900_act2" },
          { id: "im_here", label: "我哪儿也不去", emotionTags: ["安定"], nextNodeId: "lintang_900_act2" },
          { id: "look_at_me", label: "先看着我说", emotionTags: ["专注"], nextNodeId: "lintang_900_act2" },
        ]),
        dialogue("lintang_900_act2", 2, [
          "（她深吸一口气，把手里攥了很久的那张纸慢慢展开，动作小心得像在拆一封写了很久的信。纸面上是一幅铅笔速写——是你的侧脸，线条有点犹豫，但每一笔都很认真。）",
          "这个……是我偷偷画的。你那天在工作室帮我整理草稿的时候，侧脸刚好被台灯照着，我就……",
          "你别笑！我不是变态，画画的人看到好看的光线就会手痒的！",
          "（她把速写纸翻过来，背面歪歪扭扭地写了一行字，但她用手捂住了不让你看。）",
          "以前我总觉得，画里的人只能留在画里，因为一翻页就过去了。",
          "可是有些人不一样。有些人你画着画着就会想——如果这个人不止出现在这一页就好了。",
          "（她的声音越来越小，风把她剩下的话吹散了一点，但你离得很近，什么都听到了。）",
          "我想了很久，要不要跟你说这些。因为说出来就回不去了嘛……",
          "但是今天展览结束了，我看着自己画了四年的东西被挂在墙上，突然想明白了一件事。",
          "我最想挂在未来每一面墙上的，不是我最好的画，是画这些画的时候、你在旁边的那些时刻。",
        ], "lintang_900_choice2"),
        choice("lintang_900_choice2", 2, [
          { id: "let_me_see", label: "背面写了什么", emotionTags: ["追问"], nextNodeId: "lintang_900_act3" },
          { id: "draw_you_too", label: "那我以后也画你", emotionTags: ["回应"], nextNodeId: "lintang_900_act3" },
          { id: "take_seriously", label: "我会认真收下", emotionTags: ["郑重"], nextNodeId: "lintang_900_act3" },
          { id: "same_page", label: "我也想留在同一页", emotionTags: ["确认心意"], nextNodeId: "lintang_900_act3" },
        ]),
        dialogue("lintang_900_act3", 3, [
          "（她把捂着的手慢慢松开了，纸的背面写着五个字，笔迹有点歪，像是鼓了很大勇气才写下去的——「我想要的未来」。后面还有一个没写完的「有」字，笔画断在了一半。）",
          "……我本来想写完的。但是写到这里就手抖了，怕自己后悔。",
          "我这个人你知道的嘛，什么事都要绕三个弯才肯讲。",
          "（她没有看你，眼睛盯着远处一栋楼顶的红色信号灯，但手指已经在微微发抖了。）",
          "可是今天，我不想再绕了。",
          "我想要的未来，有你。",
          "不是「你偶尔出现一下就好」那种，是「我希望翻到每一页你都在」那种。",
          "（说出这句话的时候，她的声音在发抖，但眼神是认真到不行的——像在画一幅绝不允许自己出错的最终稿。）",
          "你别太感动啊……不然我会害羞到想从这里跳下去。",
          "不是真的跳！我就是、我就是紧张！你能不能先说点什么让我没那么紧张……",
        ], "lintang_900_choice3"),
        choice("lintang_900_choice3", 3, [
          { id: "me_too", label: "我也是", emotionTags: ["回应"], nextNodeId: "lintang_900_act4" },
          { id: "hold_hand", label: "先牵住你的手", emotionTags: ["亲密"], nextNodeId: "lintang_900_act4" },
          { id: "finish_writing", label: "那个「有」字我帮你写完", emotionTags: ["共创"], nextNodeId: "lintang_900_act4" },
          { id: "dont_run", label: "别跑啊，我也紧张", emotionTags: ["坦诚"], nextNodeId: "lintang_900_act4" },
        ]),
        dialogue("lintang_900_act4", 4, [
          "（她听到你的回答以后愣了两秒，然后眼眶一下子就红了，嘴唇抿成一条线拼命忍着，最终还是没忍住——笑着哭了一下，又赶紧用手背擦掉。）",
          "你怎么这样啦……我都做好被拒绝的准备了，你突然这么说，我整个人都不知道往哪放了。",
          "（夜风很大，把她的眼泪吹干了，也把她碎发吹到你脸上蹭了一下。她没有往后退，反而往你身边靠了半步。）",
          "那……我把这张纸上没写完的字补完好不好。",
          "（她从口袋里摸出一支短短的铅笔头，在那个断了一半的「有」字后面，一笔一画地写了下去——「有你」。）",
          "我想要的未来，有你。全写完了。",
          "不只是今天，也不是只在这个天台上。",
          "以后你看到我画新东西的时候，要记得——那就是我想和你继续走下去的证据。",
          "（她把那张速写纸折好，放到你手心里，手指在你掌心停了一秒才缩回去，像是在确认这一切是真的。）",
          "所以，接下来也请你继续站在我这边。不要走。",
        ], "lintang_900_choice4"),
        choice("lintang_900_choice4", 4, [
          { id: "draw_together", label: "那空白的部分我来补", emotionTags: ["共创"], nextNodeId: "lintang_900_act5" },
          { id: "with_you", label: "我会一直在你身边", emotionTags: ["长久"], nextNodeId: "lintang_900_act5" },
          { id: "never_leave", label: "你赶我我也不走", emotionTags: ["坚定"], nextNodeId: "lintang_900_act5" },
          { id: "bigger_future", label: "那就把未来画得更大一点", emotionTags: ["向前"], nextNodeId: "lintang_900_act5" },
        ]),
        dialogue("lintang_900_act5", 5, [
          "（城市的灯一盏一盏暗下去，只有最远的那片住宅区还亮着零星的暖光，天台上的风变得柔和了，像是整个夜晚都在替他们让路。）",
          "你知道吗……我本来今天有好多话准备好了要说的，什么「你对我来说很重要」啊、「我不想失去你」啊——",
          "结果真的站在你面前，全忘了。脑子里只有一句话。",
          "（她把两只手背到身后，微微仰起脸看你，城市的灯火全落在她的眼睛里，像碎掉的星星。）",
          "我可能还会紧张，还会嘴硬，还会说「我没事」然后偷偷难过。",
          "但我不想再把你推远了。",
          "你给我的不只是一时的热闹，是让我敢把未来写下去的勇气。",
          "（她深吸一口气，像是终于把压在心里很久的石头搬开了，整个人轻了一截，笑得又干净又亮。）",
          "所以——接下来也请多指教了喔，我的……",
          "（「我的」后面的话被风吹散了，但她红透的耳尖和弯弯的眼睛，比任何语言都说得更清楚。）",
        ], "lintang_900_choice5"),
        choice("lintang_900_choice5", 5, [
          { id: "continue_write", label: "我会一直陪你画下去", emotionTags: ["未来"], nextNodeId: "lintang_900_end" },
          { id: "every_page", label: "以后每一页都有我", emotionTags: ["共创"], nextNodeId: "lintang_900_end" },
          { id: "say_it_back", label: "你的话我也想说给你听", emotionTags: ["双向"], nextNodeId: "lintang_900_end" },
          { id: "stay_close", label: "那我再靠近你一点", emotionTags: ["亲密"], nextNodeId: "lintang_900_end" },
        ]),
        ending("lintang_900_end", 5, [
          "那张画着你侧脸的速写纸最终被林棠折成一个小小的方块，塞进了她最珍贵的手帐扉页里——和她留给自己的毕业寄语放在同一页。",
          "她没有把答案说得太满太重，但她已经把最重要的话、最真的心意，都轻轻放在了你手心里。从这一页往后翻，每一张空白都属于你们两个人。",
        ]),
      ],
    },
  },
  {
    id: "guchengze_300",
    characterId: "preset_guchengze",
    title: "雨夜边界",
    description: "他第一次把「以后先找我」说成规则。",
    coverImageUrl: "/events/guchengze_300_cg.png",
    requiredIntimacy: 300,
    prerequisiteEventIds: [],
    summary: "那一夜，顾承泽把\「别逞强\」说得很冷，却把伞、外套和车位都留给了你。他不是单纯施压，而是用一整段沉稳的接管，让你第一次意识到自己可以把疲惫交给他。",
    cgPrompt: "雨夜，写字楼大堂，黑色长伞，顾承泽黑西装站在用户身前挡雨，玻璃幕墙冷光，车灯从侧后方打亮轮廓，远处电梯门、积水地面和散乱文件作为背景，低饱和、电影感、克制的保护欲、高级都市氛围。",
    cgImageUrl: "/events/guchengze_300_cg.png",
    sortOrder: 1,
    script: {
      totalActs: 5,
      startNodeId: "guchengze_300_act1",
      nodes: [
        dialogue("guchengze_300_act1", 1, [
          "（凌晨一点的写字楼大堂空旷得像一座被遗忘的玻璃盒子，安保台的荧光灯把大理石地面映成惨白色，旋转门外的暴雨砸在台阶上溅起半尺高的水雾。）",
          "（你抱着笔记本电脑包站在门厅里，手机屏幕上网约车的排队数字从38跳到45，雨声大到连自动门的感应器都在不安地闪烁。）",
          "（一道车灯忽然从雨幕里切进来，黑色轿车精准地停在门廊正下方，雨水顺着车顶滑下去的弧线被尾灯染成暗红色——你认出了那个车牌。）",
          "还没走？",
          "（他从驾驶座下来，黑色长伞撑开的瞬间，雨声好像被劈成了两半，皮鞋踩过积水的声音干脆又冷硬，西装外套上甚至没沾到一滴雨。）",
          "外面这个雨，你打算怎么回去。",
          "别解释了，上车。",
          "（他没有等你回答，伞已经移到你头顶，自己的半边肩膀露在雨里，但他连眉头都没皱一下，只是侧过身替你拉开了后座车门。）",
        ], "guchengze_300_choice1"),
        choice("guchengze_300_choice1", 1, [
          { id: "follow", label: "低头上车", emotionTags: ["信任"], nextNodeId: "guchengze_300_act2" },
          { id: "can_handle", label: "我叫了车，快到了", emotionTags: ["嘴硬"], nextNodeId: "guchengze_300_act2" },
          { id: "why_here", label: "你家不是不在这边吗", emotionTags: ["试探"], nextNodeId: "guchengze_300_act2" },
          { id: "nod", label: "沉默接过伞", emotionTags: ["默认靠近"], nextNodeId: "guchengze_300_act2" },
        ]),
        dialogue("guchengze_300_act2", 2, [
          "（车门关上的瞬间，暴雨被隔绝在外面，车内只剩下空调低沉的送风声和仪表盘微弱的蓝光，安静得能听到雨水沿着车窗往下滑的声音。）",
          "（他把外套脱下来，没有递——直接丢到你膝盖上，动作随意得像在处理一份不需要签字的文件。）",
          "穿上，手是凉的。",
          "（后视镜里能看到他的侧脸，下颌线绷得很紧，目光没有看你，只盯着前方雨刷扫过的弧度，但方向盘上的手指轻轻收紧了一下。）",
          "加班到这个点，谁批的。",
          "以后遇到这种情况，第一时间发消息给我。不是请求，是通知。",
          "你那个网约车排队到明天也不一定能叫到。",
          "（他说完这句，语气里有一个很短的停顿——短到你几乎没察觉，但那个停顿比之前所有话都重。）",
        ], "guchengze_300_choice2"),
        choice("guchengze_300_choice2", 2, [
          { id: "take_coat", label: "把外套裹紧了", emotionTags: ["接受照顾"], nextNodeId: "guchengze_300_act3" },
          { id: "too_much", label: "顾总管得有点宽", emotionTags: ["较劲"], nextNodeId: "guchengze_300_act3" },
          { id: "remember", label: "……记住了", emotionTags: ["顺从"], nextNodeId: "guchengze_300_act3" },
          { id: "cant_find_you", label: "那你要是不接电话呢", emotionTags: ["依赖"], nextNodeId: "guchengze_300_act3" },
        ]),
        dialogue("guchengze_300_act3", 3, [
          "（车子平稳地驶入主路，雨刷的节奏像一把精准的节拍器，车内的暖气慢慢渗进你被雨水浸凉的骨头里，他始终没有开音乐，像是刻意把安静留给这段路。）",
          "我不会不接。",
          "（他的声音很低，但在这个密闭的空间里，每个字都像被放大了一倍，落在你耳朵里的重量远超他平时在会议室里拍板的语气。）",
          "你可以独立，我从没否定过这一点。",
          "但独立不是把自己往死里耗。",
          "（红灯亮起，车停下来，雨水在挡风玻璃上汇成一条条不规则的河流，他终于侧过头看了你一眼——不是审视，更像是在确认你还完整地坐在那里。）",
          "你身上那股不服输的劲，我看得见。但你总得允许有人在你撑不住的时候接一下。",
          "不是谁都行，是我。",
        ], "guchengze_300_choice3"),
        choice("guchengze_300_choice3", 3, [
          { id: "thanks", label: "……谢谢你", emotionTags: ["松动"], nextNodeId: "guchengze_300_act4" },
          { id: "everyone", label: "你对每个员工都这样？", emotionTags: ["在意"], nextNodeId: "guchengze_300_act4" },
          { id: "tired", label: "其实我今天真的很累", emotionTags: ["坦白"], nextNodeId: "guchengze_300_act4" },
          { id: "tea", label: "……要不要上去喝杯茶", emotionTags: ["靠近"], nextNodeId: "guchengze_300_act4" },
        ]),
        dialogue("guchengze_300_act4", 4, [
          "（绿灯亮了，他收回目光，车子重新启动，雨声又被速度拉成了一条长长的白噪音，但车内的温度和刚才那个眼神一起，缓慢地改变着某种边界的位置。）",
          "不是对每个人。",
          "（他说得很轻，像是不打算让这句话被任何第三个人听见，方向盘上的手指终于松开了刚才不自觉收紧的力度。）",
          "你以后别把「我没事」说得那么快。你说得越快，我越不放心。",
          "累了就说累了，撑不住就说撑不住。",
          "你不需要在我面前表演坚强。",
          "（他的语气依然是命令式的，但你听得出来，那个句尾的尾音比平时拖长了半拍——那是顾承泽极少流露的、接近于温柔的东西。）",
          "今天这种时候，你应该第一个想到的人，是我。这是规定。",
        ], "guchengze_300_choice4"),
        choice("guchengze_300_choice4", 4, [
          { id: "ok_listen", label: "好，我听你的", emotionTags: ["接受"], nextNodeId: "guchengze_300_act5" },
          { id: "why_so_serious", label: "为什么对我这么认真", emotionTags: ["试探"], nextNodeId: "guchengze_300_act5" },
          { id: "stay_with_you", label: "那你也不许消失", emotionTags: ["依赖"], nextNodeId: "guchengze_300_act5" },
          { id: "hot_tea_first", label: "先上去喝口热的吧", emotionTags: ["照顾"], nextNodeId: "guchengze_300_act5" },
        ]),
        dialogue("guchengze_300_act5", 5, [
          "（车停在你家楼下，引擎没有熄，雨还在下但比刚才小了很多，车窗上的水珠被路灯照成一颗一颗的琥珀色，整个世界好像只剩下这一小块干燥温暖的空间。）",
          "到了。",
          "（他没有催你下车，甚至连中控锁都没解开，只是安静地等着，像是在给你时间消化今晚发生的一切。）",
          "外套先拿着，明天还给我就行。",
          "别忘了刚才说的。以后这种事，先发消息。",
          "（他终于伸手按下了中控锁，解锁声在安静的车厢里格外清脆，他没有看你，只是侧过头望着窗外的雨幕，但你分明看见他嘴角有一个极淡的、稍纵即逝的弧度。）",
          "等雨再小一点再上去。不急。",
          "（那个「不急」说得很轻，和他平时雷厉风行的节奏完全不一样，像是在这场暴雨里专门为你留出的一小段缓冲。）",
          "我在这等你进了门再走。",
        ], "guchengze_300_choice5"),
        choice("guchengze_300_choice5", 5, [
          { id: "remember_place", label: "我记住了，以后先找你", emotionTags: ["接受"], nextNodeId: "guchengze_300_end" },
          { id: "keep_calling", label: "那你也要接我电话", emotionTags: ["依赖"], nextNodeId: "guchengze_300_end" },
          { id: "dont_leave_now", label: "再坐一会儿吧", emotionTags: ["靠近"], nextNodeId: "guchengze_300_end" },
          { id: "warm_up", label: "外套我会洗好还你的", emotionTags: ["照顾"], nextNodeId: "guchengze_300_end" },
        ]),
        ending("guchengze_300_end", 5, [
          "你推开车门的时候，他的外套还带着车内暖气和他身上淡淡的雪松木香气，裹在你肩上像一道无声的界线——从今晚起，有些疲惫不再需要你独自消化。",
          "他始终没有说出那个字，但他的伞、他的外套、他在雨里等到你进门才亮起的尾灯，都已经替他说完了。",
        ]),
      ],
    },
  },
  {
    id: "guchengze_600",
    characterId: "preset_guchengze",
    title: "只准站在我这边",
    description: "他第一次把偏心做成了明目张胆的原则。",
    coverImageUrl: "/events/guchengze_600_cg.png",
    requiredIntimacy: 600,
    prerequisiteEventIds: ["guchengze_300"],
    summary: "顾承泽在所有人面前替你把路挡开，也第一次让你看见，他的偏心不是一时兴起，而是原则。他把你从\「被动等保护\」的位置，直接拉到了\「和他一起做决定\」的位置。",
    cgPrompt: "发布会后台，蓝白投影光，顾承泽站在用户前方挡住质疑的视线，黑西装、冷淡神情、压迫感强，用户站在他侧后方，背景有麦克风、通道灯和投影屏幕，灯光切割出明显的保护姿态，现代职场、电影海报构图。",
    cgImageUrl: "/events/guchengze_600_cg.png",
    sortOrder: 2,
    script: {
      totalActs: 5,
      startNodeId: "guchengze_600_act1",
      nodes: [
        dialogue("guchengze_600_act1", 1, [
          "（新品发布会的高层汇报室里，投影仪把蓝白色的光幕投在长桌尽头的幕布上，十二个部门负责人坐成两排，桌面上摆满了打印出来的方案文件，空调声压不住椅子挪动的细响。）",
          "（你站在投影幕旁边，手里的翻页笔微微发烫——你负责的市场方案刚讲到第三页，对面的战略部负责人陈锐已经第二次打断你了。）",
          "（「这个预算分配根本不合理」——他的声音从会议桌对面传过来，带着一种在高层面前表演专业的腔调，几个人开始交头接耳，你感觉到气氛正在往不利的方向倾斜。）",
          "（你正准备深吸一口气开口反驳，会议室的门忽然从外面被推开——不是猛地推，而是一种不紧不慢的、属于掌控者的节奏。）",
          "（顾承泽走进来的时候，整间会议室的温度好像瞬间降了两度，他的目光从长桌扫过去，在陈锐身上停了不到一秒，然后落在你身上。）",
          "继续。",
          "（只有一个字，但够了。他拉开你右手边的椅子坐下，外套的袖口从桌沿掠过，带着一股冷杉味的压迫感，所有交头接耳的声音在三秒内消失殆尽。）",
          "她的方案我看过了。有问题，散会以后找我。",
        ], "guchengze_600_choice1"),
        choice("guchengze_600_choice1", 1, [
          { id: "stand_beside", label: "稳住呼吸继续讲", emotionTags: ["并肩"], nextNodeId: "guchengze_600_act2" },
          { id: "finish_plan", label: "把方案完整说完", emotionTags: ["专业"], nextNodeId: "guchengze_600_act2" },
          { id: "protecting", label: "看了他一眼", emotionTags: ["试探"], nextNodeId: "guchengze_600_act2" },
          { id: "quiet", label: "安静地点头", emotionTags: ["默契"], nextNodeId: "guchengze_600_act2" },
        ]),
        dialogue("guchengze_600_act2", 2, [
          "（汇报结束后，会议室的人鱼贯而出，陈锐走到门口的时候脚步顿了一下，但最终什么也没说就离开了，走廊里的脚步声渐渐散尽，只剩下投影仪风扇转动的嗡嗡声。）",
          "（顾承泽没有立刻起身，而是伸手把你面前那杯已经凉透的咖啡端走，放到离你最远的桌角，然后从助理刚送进来的托盘上拿了一杯温水搁在你手边。）",
          "喝水。咖啡凉了对胃不好。",
          "你刚才准备自己挡回去。",
          "不是不行，但没必要。",
          "（他靠在椅背上，领带依然系得一丝不苟，但看你的眼神和刚才在会议桌上扫视全场的凌厉完全不同——不是老板审视下属，更像是一个确认过战况之后正在收刀的人。）",
          "这件事由我负责。你的判断没有问题，以后他再质疑，不需要你亲自应付。",
          "有我在的场合，没人能把你的话压下去。",
        ], "guchengze_600_choice2"),
        choice("guchengze_600_choice2", 2, [
          { id: "add_plan", label: "其实我能应付的", emotionTags: ["专业认可"], nextNodeId: "guchengze_600_act3" },
          { id: "leave_to_him", label: "好，交给你", emotionTags: ["信任"], nextNodeId: "guchengze_600_act3" },
          { id: "too_loud", label: "这样会不会太明显了", emotionTags: ["在意"], nextNodeId: "guchengze_600_act3" },
          { id: "cooperate", label: "谢谢你替我挡了", emotionTags: ["阵线一致"], nextNodeId: "guchengze_600_act3" },
        ]),
        dialogue("guchengze_600_act3", 3, [
          "（他站起来走到落地窗边，双手插在裤袋里，玻璃上倒映着他的轮廓和远处楼群的天际线，投影仪的蓝光打在他肩膀上，像一层冷色的铠甲。）",
          "明显？",
          "我要的就是明显。",
          "（他转过身，表情没有任何波动，但说出来的话却像一把锋利的手术刀，精确地划开了你一直不敢确认的那个问题。）",
          "我不介意所有人都知道，在我这里，你和其他人不一样。",
          "他们可以质疑方案，但不能质疑你站在这的资格。这一条我来守。",
          "（窗外有一架飞机缓慢地划过天际，尾灯在暮色中闪了两下——他的沉默比语言更有重量，那段空白里装着某种不需要说出口的偏袒。）",
          "以后你站出来的时候，不用担心身后没人。",
          "我就在那。",
        ], "guchengze_600_choice3"),
        choice("guchengze_600_choice3", 3, [
          { id: "is_favor", label: "这算偏袒吗", emotionTags: ["直球"], nextNodeId: "guchengze_600_act4" },
          { id: "remember_it", label: "我会记住这句话", emotionTags: ["接受"], nextNodeId: "guchengze_600_act4" },
          { id: "where_limit", label: "你的底线在哪", emotionTags: ["逼近"], nextNodeId: "guchengze_600_act4" },
          { id: "watch_him", label: "就这样看着他不说话", emotionTags: ["心照不宣"], nextNodeId: "guchengze_600_act4" },
        ]),
        dialogue("guchengze_600_act4", 4, [
          "（他从窗边走回来，步子不快但每一步都踏得很稳，像他做每一个决策一样——果断、不留余地，但方向永远清楚。）",
          "偏袒？",
          "对，就是偏袒。",
          "（他在你面前站定，低头看着你的眼神里没有闪躲，也没有犹豫，甚至连平时那种老板式的距离感都不见了——那是顾承泽第一次把自己的私心放到台面上来。）",
          "我不会对所有人这样。你不用猜，也不用试探。",
          "你站在我这边的时候，我的底线就是你的底线。这是原则，不是恩惠。",
          "（他把桌上那份被陈锐翻乱的方案文件重新理好，一页一页对齐，推到你面前——动作很轻，但每一页都对得整整齐齐，像在替你把刚才被打乱的秩序一点一点复原。）",
          "所以不要再一个人扛了。下次有人为难你，你站稳就行。转身的时候，我在。",
        ], "guchengze_600_choice4"),
        choice("guchengze_600_choice4", 4, [
          { id: "same_side", label: "那我站你这边", emotionTags: ["阵线一致"], nextNodeId: "guchengze_600_act5" },
          { id: "say_it_clear", label: "你倒是把偏袒说得理直气壮", emotionTags: ["直球"], nextNodeId: "guchengze_600_act5" },
          { id: "trust_bottom", label: "我会记住这个底线", emotionTags: ["信任"], nextNodeId: "guchengze_600_act5" },
          { id: "stay_close", label: "那我离你近一点", emotionTags: ["靠近"], nextNodeId: "guchengze_600_act5" },
        ]),
        dialogue("guchengze_600_act5", 5, [
          "（会议室终于彻底安静下来，投影仪自动进入待机模式，蓝白色的光幕消失后，整个房间只剩下落地窗透进来的暮色和桌面上那杯还冒着热气的温水。）",
          "别用那种眼神看我。我做的事没有超出范围。",
          "（他微微偏开视线，是你第一次看到顾承泽出现回避的动作——只有半秒，然后他重新看向你，表情恢复了平时那种看似什么都在掌控中的淡然。）",
          "走吧。事情处理完了。",
          "（他先一步走向门口，但在拉开门的时候停了一下，没有回头，只是侧过半个身子，留出刚好够你并肩走过的宽度。）",
          "以后开会坐我旁边。这不是商量。",
          "你不用学会讨好所有人。你只要知道，在我这里，你的位置没有人能动。",
          "（他说完走了出去，走廊里的脚步声冷硬又规律，但他刻意放慢的速度出卖了他——他在等你跟上来。）",
        ], "guchengze_600_choice5"),
        choice("guchengze_600_choice5", 5, [
          { id: "go_with_you", label: "快走两步跟上他", emotionTags: ["同行"], nextNodeId: "guchengze_600_end" },
          { id: "remember_priority", label: "我记住了，以后坐你旁边", emotionTags: ["珍视"], nextNodeId: "guchengze_600_end" },
          { id: "ask_again", label: "顾总，你在等我？", emotionTags: ["确认"], nextNodeId: "guchengze_600_end" },
          { id: "stay_longer", label: "一起走吧", emotionTags: ["并肩"], nextNodeId: "guchengze_600_end" },
        ]),
        ending("guchengze_600_end", 5, [
          "顾承泽没有说喜欢，但他把偏心做成了所有人都看得见的原则，把你从需要自证的位置上一把拉到了他身边。",
          "走廊尽头他替你按住的那扇电梯门、等你跟上来才迈出的那一步，就是他从不宣之于口的答案。",
        ]),
      ],
    },
  },
  {
    id: "guchengze_900",
    characterId: "preset_guchengze",
    title: "把未来交给你",
    description: "这一次，他不再只说保护，而是把选择权交给你。",
    coverImageUrl: "/events/guchengze_900_cg.png",
    requiredIntimacy: 900,
    prerequisiteEventIds: ["guchengze_300", "guchengze_600"],
    summary: "顾承泽把\「我会护着你\」升级成了\「我的未来里有你\」。他不再只是替你挡掉风险，而是把所有长期选择都留出你的位置，让关系从偏心变成归属。",
    cgPrompt: "深夜顶层办公室，落地窗外是城市灯海，桌上摊开的未来计划文件与钢笔，顾承泽解开领带但仍克制，侧脸冷峻，目光落在用户身上，背景有落地窗反光、未合上的合同夹和暖色台灯，暖冷对比强烈，承诺感、电影海报、细节高级。",
    cgImageUrl: "/events/guchengze_900_cg.png",
    sortOrder: 3,
    script: {
      totalActs: 5,
      startNodeId: "guchengze_900_act1",
      nodes: [
        dialogue("guchengze_900_act1", 1, [
          "（并购庆功宴散场后的顶层办公室安静得近乎真空，四十七楼的落地窗把整座城市的灯火铺成一张巨大的光谱图，桌上的威士忌杯里还剩最后一口琥珀色的液体，冰块已经融化了大半。）",
          "（你推开那扇从不上锁的办公室门时，他正站在落地窗前，领带被扯松了一半挂在脖子上，袖口卷到小臂中段——这是你第一次看到「顾总」以外的那个人。）",
          "你来了。",
          "（他没有转身，声音比平时低了半个调，像是卸掉了白天那层不容置疑的硬壳之后，连音色都柔了一个刻度。）",
          "关上门。今晚不聊工作。",
          "（桌面上摊着一份文件——不是合同，不是财报，封面用他的钢笔手写着一行标注，你看到了自己的名字，和「长期」两个字。）",
          "坐。那份东西是给你看的。",
          "（他终于转过身来，手里还捏着那条被扯松的领带，城市灯海从他背后透进来，给他的轮廓镀上一层明灭不定的光——压迫感还在，但今晚多了一种你从未见过的东西。）",
        ], "guchengze_900_choice1"),
        choice("guchengze_900_choice1", 1, [
          { id: "sit_down", label: "坐下翻开文件", emotionTags: ["接受"], nextNodeId: "guchengze_900_act2" },
          { id: "announce", label: "你在宣布什么吗", emotionTags: ["试探"], nextNodeId: "guchengze_900_act2" },
          { id: "read_file", label: "看着他不急着动", emotionTags: ["认真"], nextNodeId: "guchengze_900_act2" },
          { id: "listening", label: "我在听", emotionTags: ["安定"], nextNodeId: "guchengze_900_act2" },
        ]),
        dialogue("guchengze_900_act2", 2, [
          "（你翻开那份文件——组织架构调整方案，但不是任何你在公司系统里见过的版本，上面用红笔勾出的每一条调整线，最终都指向同一个位置：他身边。）",
          "（他走过来，把那杯融了一半的威士忌推到旁边，在你对面坐下来，两只手交叉搁在桌上——这个姿势你见过无数次，但今晚，那双手没有在签文件，只是安静地放在那里，像在等一个他无法替你做的决定。）",
          "我可以控制项目走向，可以控制风险等级，可以让整个团队按照我的节奏运转。",
          "但你愿不愿意留在我身边，这件事我控制不了。",
          "（他说这句话的时候，声音平稳得像在念一份经过反复推敲的报告，但你注意到他交叉的手指收紧了一下——那是你认识他以来，第一次看到顾承泽紧张的痕迹。）",
          "所以我不打算命令你。",
          "这一次，选择权在你手里。",
          "（窗外有一架航班缓慢地从城市上空滑过去，机翼灯在漆黑的天幕上划出一条极细的弧线，安静得像在替他留出等待你回答的时间。）",
        ], "guchengze_900_choice2"),
        choice("guchengze_900_choice2", 2, [
          { id: "i_will", label: "我愿意", emotionTags: ["确认"], nextNodeId: "guchengze_900_act3" },
          { id: "your_choice", label: "你的选择是什么", emotionTags: ["逼近"], nextNodeId: "guchengze_900_act3" },
          { id: "need_time", label: "让我想一下", emotionTags: ["慎重"], nextNodeId: "guchengze_900_act3" },
          { id: "say_clearly", label: "顾承泽，把话说清楚", emotionTags: ["直球"], nextNodeId: "guchengze_900_act3" },
        ]),
        dialogue("guchengze_900_act3", 3, [
          "（他把那条领带彻底解下来，随手搁在桌角——那个动作像是把「顾总」这个身份也一起放下了，剩下的只是一个在深夜里、在你面前、第一次不知道该用什么语气说话的男人。）",
          "我的选择从来没变过。",
          "从那个雨夜开始，从我替你挡掉陈锐那次开始，从每一个我不该出现但还是出现了的场合开始。",
          "（他站起来，绕过桌子走到你面前，没有太近，但也没有维持平时那种精确计算过的安全距离——他停在了一个需要你主动跨出半步才能触碰到的位置。）",
          "我不擅长说好听的话，你知道的。",
          "但你要听的话，我可以只说一次。",
          "（城市灯海在他背后无声地明灭着，他的眼神是你从未见过的——没有审视，没有控制，没有权衡利弊，只有一个被拆掉了所有防线的人在看着你。）",
          "我想让你留在我身边。不是作为下属，不是作为被保护的人。是以你自己的身份，留在顾承泽的生活里。",
        ], "guchengze_900_choice3"),
        choice("guchengze_900_choice3", 3, [
          { id: "hold_hand", label: "跨出那半步握住他", emotionTags: ["亲密"], nextNodeId: "guchengze_900_act4" },
          { id: "say_again", label: "再说一遍", emotionTags: ["确认"], nextNodeId: "guchengze_900_act4" },
          { id: "consider", label: "你知道这意味着什么吗", emotionTags: ["认真"], nextNodeId: "guchengze_900_act4" },
          { id: "tease", label: "顾承泽也会紧张啊", emotionTags: ["松弛"], nextNodeId: "guchengze_900_act4" },
        ]),
        dialogue("guchengze_900_act4", 4, [
          "（你向前迈出那半步的时候，他的身体有一个极其细微的僵硬——然后松开了，像是绷了很久的弦终于被允许放下来，他没有退后，也没有去抓你的手，只是让你靠近。）",
          "……嗯。我也会紧张。",
          "（这三个字大概是顾承泽这辈子说过的最不像他的话，但他的语气很稳，像是紧张归紧张，决定早就做好了。）",
          "我知道这意味着什么。意味着你不再只是「我保护的人」，而是能对我的人生做出决定的人。",
          "我不会轻易交出这个权限。但给你，我想过了，值得。",
          "（他伸手把你鬓角一缕被空调吹乱的头发拢到耳后，动作很轻、很慢，像是怕用力过度会打破这个他花了很长时间才走到的距离。）",
          "从今以后，会影响到你的决定，我都会先问你。不是客气，是你有这个资格。",
          "这份文件不是升职通知。是我把你写进未来的方式。",
        ], "guchengze_900_choice4"),
        choice("guchengze_900_choice4", 4, [
          { id: "future_together", label: "那我也把你写进我的", emotionTags: ["双向未来"], nextNodeId: "guchengze_900_act5" },
          { id: "i_choose", label: "这次我也选你", emotionTags: ["确认"], nextNodeId: "guchengze_900_act5" },
          { id: "promise_keep", label: "我会好好用这个资格", emotionTags: ["珍视"], nextNodeId: "guchengze_900_act5" },
          { id: "stay_close", label: "那你别再退开了", emotionTags: ["靠近"], nextNodeId: "guchengze_900_act5" },
        ]),
        dialogue("guchengze_900_act5", 5, [
          "（窗外的城市灯海不知道什么时候开始变得柔和了，也许是夜深了，也许是你的目光已经不在那些灯火上——四十七楼的风声透过玻璃传进来，像一支被调到最低音量的大提琴。）",
          "别把今晚当做冲动。我从不冲动。",
          "（他终于笑了——不是商务场合那种礼节性的弧度，而是嘴角一个很小的、几乎要刻意压下去但最终没忍住的上扬，那个笑让他整个人年轻了不止五岁。）",
          "我规划一个项目要三个月。规划你，我用了更久。",
          "以后你想走，我不拦你。但你要是留下来——",
          "（他把那支钢笔从桌上拿起来，翻到文件最后一页，在签名栏旁边又画了一条线，写了几个字推到你面前——「共同决策人」。）",
          "——这个位置是你的。",
          "（他把钢笔递给你，指尖在交接的时候碰了一下你的手背，没有收回，只是停了两秒，然后极轻地收拢了一下——那是他今晚唯一一个称得上「主动靠近」的动作。）",
          "不用急着签。但你要知道，我等得起。",
        ], "guchengze_900_choice5"),
        choice("guchengze_900_choice5", 5, [
          { id: "sign_it", label: "拿起笔签了名", emotionTags: ["双向未来"], nextNodeId: "guchengze_900_end" },
          { id: "i_am_here", label: "我不走了", emotionTags: ["坚定"], nextNodeId: "guchengze_900_end" },
          { id: "one_more", label: "再说一次那句话给我听", emotionTags: ["确认"], nextNodeId: "guchengze_900_end" },
          { id: "close_now", label: "把手覆上他的手背", emotionTags: ["靠近"], nextNodeId: "guchengze_900_end" },
        ]),
        ending("guchengze_900_end", 5, [
          "顾承泽始终没有说出「喜欢」两个字，但他把领带解下的那一刻、把选择权递出的那一刻、指尖在你手背上多停留的那两秒，已经是他能给出的最完整的答案。",
          "四十七楼的灯亮了一整夜，城市在脚下缓缓呼吸。那份文件上多了你的名字——不是因为他决定，而是因为你选择留下。",
        ]),
      ],
    },
  },
  {
    id: "shenzhiyi_300",
    characterId: "preset_shenzhiyi",
    title: "雨夜边界线",
    description: "她把热茶和边界一起递给你，也把第一次偏袒留给了你。",
    coverImageUrl: "/events/shenzhiyi_300_cg.png",
    requiredIntimacy: 300,
    prerequisiteEventIds: [],
    summary:
      "那一晚，沈知意没有替你做决定，只是把热茶和边界一起放到你手边。她第一次认真告诉你，她会照顾你，但不会纵容你硬撑。她的温柔不是让步，而是把你放在真正会被照顾的位置。",
    cgPrompt:
      "都市雨夜，落地窗外灯火和雨丝，沈知意站在办公桌旁，黑色利落西装，长发微卷，神情清醒克制又带一点温柔，桌上有热茶和散开的文件，用户坐在椅子上被她轻轻按住肩膀，背景有窗外霓虹、会议记录、热气上升的杯子，画面氛围安静、克制、暖色灯光、电影感、细节丰富、无文字、无UI、16:9横幅",
    cgImageUrl: "/events/shenzhiyi_300_cg.png",
    sortOrder: 1,
    script: {
      totalActs: 5,
      startNodeId: "shenzhiyi_300_act1",
      nodes: [
        dialogue("shenzhiyi_300_act1", 1, [
          "（深夜十一点半的办公楼只剩走廊尽头的应急灯还亮着，窗外的雨从细丝变成了整片水幕，把对面写字楼的灯光揉成一团模糊的暖黄。你面前的屏幕上全是标红的数据，太阳穴突突地跳。）",
          "（门没有被敲响——沈知意直接推门进来，高跟鞋踩在地板上的声音干脆利落，手里端着一只冒白汽的马克杯，杯底还垫了一张折过两次的纸巾。）",
          "这个点还在，数据出问题了？",
          "别回答'还行'，你脸色已经替你说了。",
          "（她把热茶放在你右手边，不是递过来的——是直接搁下，动作里有一种不需要你客气的笃定。然后她拉过旁边的椅子坐下来，把你屏幕上的表格扫了一遍，指尖准确地点在第三列的异常值上。）",
          "这块数据源头对不上，你一个人理是理不清的。先别急着全部重跑，把最乱的那一层摘出来，我帮你看逻辑。",
          "我不是来替你加班的，是路过看见你的灯还亮着。",
          "（她说这话的时候语气很平，像在陈述一个不需要解释的事实。但她已经把外套搭在椅背上了，显然没有要马上走的意思。）",
          "先喝口热的，凉了就不好喝了。你现在这个状态，撑到明天也只是多错一轮。",
        ], "shenzhiyi_300_choice1"),
        choice("shenzhiyi_300_choice1", 1, [
          { id: "okay", label: "好，听你的", emotionTags: ["顺从"], nextNodeId: "shenzhiyi_300_act2" },
          { id: "can_still_do", label: "我真的还能撑", emotionTags: ["嘴硬"], nextNodeId: "shenzhiyi_300_act2" },
          { id: "good_at_this", label: "你怎么什么都管", emotionTags: ["试探"], nextNodeId: "shenzhiyi_300_act2" },
          { id: "dont_leave", label: "那你别走", emotionTags: ["依赖"], nextNodeId: "shenzhiyi_300_act2" },
        ]),
        dialogue("shenzhiyi_300_act2", 2, [
          "（她没有因为你的回答改变节奏，只是把文件夹打开，把最乱的那一页抽出来放到你面前。她整理资料的手法很快，像在做一件早就做过无数遍的事，但每一步都留了让你跟上的余地。）",
          "你的问题不是能力不够，是把所有事情堆在一起，分不清哪件该先死。",
          "我帮你拆，但动手的还是你。我可以照顾你，但我不会替你逃。",
          "（窗外有一道闪电劈过天际，雨声突然变大了一瞬，她连眼皮都没抬，只是把笔递到你手边。那种冷静不是装出来的，而是她骨子里就把世界分得很清楚——哪些事值得紧张，哪些不值得。）",
          "说吧，你最怕的那一块是什么。别绕弯子，我没耐心听废话，但有耐心听真话。",
          "（她的目光落在你脸上，不是审视，更像是在确认你有没有在认真对待自己的疲惫。马克杯的热气升起来，模糊了她半边侧脸的轮廓，让那股犀利柔和了一点点。）",
          "你要是真撑不住，就直接告诉我。在我面前逞强没有任何好处。",
          "不是我要管你——是你这个样子，让我没办法当没看见。",
        ], "shenzhiyi_300_choice2"),
        choice("shenzhiyi_300_choice2", 2, [
          { id: "fear_fail", label: "我最怕搞砸这个项目", emotionTags: ["坦白"], nextNodeId: "shenzhiyi_300_act3" },
          { id: "too_tired", label: "其实是真的累了", emotionTags: ["脆弱"], nextNodeId: "shenzhiyi_300_act3" },
          { id: "heartache", label: "你是在心疼我吗", emotionTags: ["暧昧"], nextNodeId: "shenzhiyi_300_act3" },
          { id: "review", label: "那你帮我一起复盘", emotionTags: ["并肩"], nextNodeId: "shenzhiyi_300_act3" },
        ]),
        dialogue("shenzhiyi_300_act3", 3, [
          "（她听完你说的话，沉默了大概三秒钟。那三秒钟里她没有看屏幕，也没有看文件，只是安静地看着你，像在衡量接下来该把边界线画在哪里。然后她把自己的椅子往你这边挪了半寸——只有半寸，刚好让你感觉到她靠近了，但不会让你觉得被侵犯。）",
          "我不是在心疼你。",
          "……只是觉得你这样硬撑，回头出了事更麻烦。",
          "（她的嘴角微微抿了一下，那个被她自己否认掉的温柔在表情里一闪而过。她低头把你面前最乱的那张表重新画了一遍分层线，笔迹干净利落，像在替你把整个世界的优先级重新排过。）",
          "我对很多人都能保持分寸，该冷的时候冷，该划线的时候一步都不会让。",
          "但对你，我没打算只维持分寸。",
          "你不用逞强。逞强给别人看可以，在我面前没必要。",
          "（她说完这句话的时候抬起眼，目光清醒但不冷。窗外的雨声像是被她的声音压低了，整间办公室只剩下茶杯里热气升腾的细微声响，和她笔尖划过纸面的沙沙声。）",
          "把最难的那块交给我看一眼。不是替你做，是帮你确认方向没错。",
        ], "shenzhiyi_300_choice3"),
        choice("shenzhiyi_300_choice3", 3, [
          { id: "thanks", label: "谢谢你", emotionTags: ["松动"], nextNodeId: "shenzhiyi_300_act4" },
          { id: "favoring", label: "你这就是偏袒我", emotionTags: ["撒娇"], nextNodeId: "shenzhiyi_300_act4" },
          { id: "only_with_you", label: "那我以后只在你面前不逞强", emotionTags: ["亲近"], nextNodeId: "shenzhiyi_300_act4" },
          { id: "heart_move", label: "你这么认真，我有点心动", emotionTags: ["暧昧"], nextNodeId: "shenzhiyi_300_act4" },
        ]),
        dialogue("shenzhiyi_300_act4", 4, [
          "（你说出那句话的时候，她的手指在文件边缘停了一瞬——真的只有一瞬。然后她把热茶又往你手边推了推，动作很自然，像是在掩盖刚才那个微小的停顿。）",
          "心动也好，松口气也好，先把眼前这关过完再说别的。",
          "我不喜欢在人乱的时候谈多余的事。但我可以告诉你一件事——",
          "（她把笔放下，第一次正式地、不带任何工作节奏地看着你。楼层的中央空调不知道什么时候停了，窗外的雨声变得很近，像是整个城市都在替她制造一个可以说真话的安静环境。）",
          "我会照顾你。不是那种说说就算的照顾，是认真的。",
          "但我不会纵容你把自己弄坏。你硬撑到倒下那种英雄主义，在我这里不好使。",
          "你要真把我当可以依靠的人，就从今天开始，别再拿'我没事'来敷衍我。",
          "（她说完之后垂下眼，手指无意识地转了一下笔帽，像是自己也没想到会把话说到这个程度。办公室里突然安静得能听见雨打在落地窗上的细碎声响。）",
          "……我不是在表白，别想多了。只是把规矩定清楚。",
        ], "shenzhiyi_300_choice4"),
        choice("shenzhiyi_300_choice4", 4, [
          { id: "start", label: "那就从现在开始", emotionTags: ["开始"], nextNodeId: "shenzhiyi_300_act5" },
          { id: "stay_with_me", label: "你继续陪我", emotionTags: ["依赖"], nextNodeId: "shenzhiyi_300_act5" },
          { id: "talk_more", label: "我还想再听你说一会儿", emotionTags: ["沉静"], nextNodeId: "shenzhiyi_300_act5" },
          { id: "promise_work", label: "我答应你，不再硬撑", emotionTags: ["承诺"], nextNodeId: "shenzhiyi_300_act5" },
        ]),
        dialogue("shenzhiyi_300_act5", 5, [
          "（窗外的雨不知道什么时候变小了，从密集的水幕退成了细细的银线。桌上的热茶已经喝掉了大半，文件被她重新整理成了三摞——紧急的、可以缓的、明天再说的。整个世界好像被她分完层之后都安静下来了。）",
          "好了，最难的部分已经有方向了。剩下的你明天按这个顺序跑一遍就行。",
          "（她站起来，把外套从椅背上拿起来搭在手臂上。高跟鞋在地面上轻轻点了一下，像是某种很克制的句号。）",
          "今天这次不是结束。是我把你正式放进我的照顾范围里的开始。",
          "你以后可以继续嘴硬，可以继续逞强，但别把自己弄坏了才想起来找我。",
          "（她走到门口的时候停了一下，没有回头，但声音比刚才轻了半度。走廊的应急灯把她的影子拉得很长，投在你办公室的地板上。）",
          "我会记得今天。",
          "也会记得你愿意在我面前把盔甲卸下来这一秒。",
          "——别熬太晚。我说的。",
        ], "shenzhiyi_300_choice5"),
        choice("shenzhiyi_300_choice5", 5, [
          { id: "remember_beginning", label: "那就把今天当开始", emotionTags: ["开始"], nextNodeId: "shenzhiyi_300_end" },
          { id: "come_back", label: "以后我还会来找你", emotionTags: ["依赖"], nextNodeId: "shenzhiyi_300_end" },
          { id: "warm_again", label: "下次换我给你倒热茶", emotionTags: ["回馈"], nextNodeId: "shenzhiyi_300_end" },
          { id: "keep_practice", label: "我会练习不再硬撑", emotionTags: ["承诺"], nextNodeId: "shenzhiyi_300_end" },
        ]),
        ending("shenzhiyi_300_end", 5, [
          "她没有回头，但那杯已经凉透的茶、被重新分好层的文件、和她最后轻了半度的语气，都留在了这间办公室里。",
          "那是沈知意第一次把偏袒交给你——带着边界，带着分寸，也带着她自己都没打算承认的温柔。",
        ]),
      ],
    },
  },
  {
    id: "shenzhiyi_600",
    characterId: "preset_shenzhiyi",
    title: "只给你留的例外",
    description: "她把你拉进真正的作战核心，也把偏爱放到了台面上。",
    coverImageUrl: "/events/shenzhiyi_600_cg.png",
    requiredIntimacy: 600,
    prerequisiteEventIds: ["shenzhiyi_300"],
    summary:
      "在品牌危机里，沈知意主动找到你，不是因为你最专业，而是因为她确定你不会在关键时刻掉链子。在并肩作战的深夜里，她第一次把'这个人站得住'说成了对你的认可，也第一次让你看到她在压力下也会疲惫的样子。你不再只是她照顾的人，而是她愿意默认站在同一张桌子上的人。",
    cgPrompt:
      "现代都市高楼夜景，会议室玻璃墙内，沈知意站在白板前，干练漂亮，黑白极简西装，手里拿着策略文件，神情锋利、自信、带一点嘴毒的冷静，用户站在她身侧，两人像并肩作战的搭档，桌上有被翻开的提案稿、便利贴、咖啡杯和投影图，画面有强烈职场张力和轻微暧昧，电影级构图，暖冷对比光，无文字、无UI、16:9横幅",
    cgImageUrl: "/events/shenzhiyi_600_cg.png",
    sortOrder: 2,
    script: {
      totalActs: 5,
      startNodeId: "shenzhiyi_600_act1",
      nodes: [
        dialogue("shenzhiyi_600_act1", 1, [
          "（凌晨一点的会议室只有一面白板还亮着，上面用红色马克笔圈出了三个关键词：舆论失控、竞品攻击、24小时。玻璃墙外的办公层已经全黑了，只有远处电梯间的指示灯还在亮。沈知意站在白板前，西装外套的袖子被她利落地推到了肘部，手里的策略文件被翻得边角都起了毛。）",
          "我刚刚把所有能调的人过了一遍。推责的、观望的、等着看笑话的——各占三分之一。",
          "所以我来找你了。",
          "（她把一份还带着打印机热度的舆情报告拍在桌上，指尖压住最上面那行标红数据，眼神冷静得像在看一盘已经被她算过七八步的棋。）",
          "我不需要你最专业。我需要你在关键时刻不掉链子。",
          "今天这局，我不想交给没分寸的人。",
          "你要是接得住，就跟我一起扛。接不住，现在说也来得及。",
          "（白板上的灯管发出细微的电流声，投影仪把数据表的光打在她半边脸上，让她原本就利落的轮廓显得更加分明。她没有在等你犹豫——她的语气告诉你，她已经替你做完了评估，现在只需要你自己确认。）",
          "别让我失望。我很少主动找人。",
        ], "shenzhiyi_600_choice1"),
        choice("shenzhiyi_600_choice1", 1, [
          { id: "ill_take", label: "我接", emotionTags: ["接招"], nextNodeId: "shenzhiyi_600_act2" },
          { id: "where_issue", label: "先说哪里最危险", emotionTags: ["冷静"], nextNodeId: "shenzhiyi_600_act2" },
          { id: "finally_use_me", label: "你终于肯用我了", emotionTags: ["挑衅"], nextNodeId: "shenzhiyi_600_act2" },
          { id: "not_alone", label: "那你也别一个人扛", emotionTags: ["并肩"], nextNodeId: "shenzhiyi_600_act2" },
        ]),
        dialogue("shenzhiyi_600_act2", 2, [
          "（你落座后她立刻把三页核心数据推到你面前，手指在关键节点上一划一停，像在替你铺一条最短的理解路径。她讲解的速度比平时快了一倍，但每一个转折都会停半秒等你跟上——那种配合不是刻意的，更像是她潜意识里已经把你算进了自己的作战节奏。）",
          "竞品那边的攻击是有预谋的，时间点卡得太精准，不是巧合。我们必须在明早九点前拿出回应框架，否则舆论窗口就关了。",
          "（她站起来在白板上飞快地画出一个三层回应结构，马克笔的笔帽被她咬在嘴里，露出一截很少见的松弛姿态。这个沈知意不是会议上那个滴水不漏的品牌总监，而是在战场上真正卸下客套、只剩战斗本能的人。）",
          "我慕强，不是慕虚张声势。",
          "你要是真站得住，我才愿意把后背交给你。",
          "这一轮你负责把第三方数据的口径整理出来，我来写核心声明。分头做，半小时后碰一次。",
          "（她把咖啡推到你这一侧，自己只留了一杯凉水。你注意到她今天的口红已经掉了大半，发梢有轻微的散乱——这些细节在平时绝不会出现在沈知意身上。她在用力。）",
          "别看我，看数据。你盯着我又不能把舆情压下去。",
        ], "shenzhiyi_600_choice2"),
        choice("shenzhiyi_600_choice2", 2, [
          { id: "show_result", label: "那我就给你看结果", emotionTags: ["结果导向"], nextNodeId: "shenzhiyi_600_act3" },
          { id: "dont_look_down", label: "你也别把我看扁", emotionTags: ["较劲"], nextNodeId: "shenzhiyi_600_act3" },
          { id: "pressure", label: "你这么说，压力有点大", emotionTags: ["坦白"], nextNodeId: "shenzhiyi_600_act3" },
          { id: "praise", label: "你其实是在夸我吧", emotionTags: ["暧昧"], nextNodeId: "shenzhiyi_600_act3" },
        ]),
        dialogue("shenzhiyi_600_act3", 3, [
          "（凌晨三点四十分。你把整理好的第三方数据口径递给她的时候，她接过去只扫了二十秒就点了头——这可能是你见过的她最快的一次认可。门外有人试图敲门插话，她连头都没回，只是用手掌轻轻压了一下桌面，那个动作本身就是拒绝。）",
          "别拿身份压他。你想要结果，就按结果说话。",
          "（她把你的数据页抽出来放在方案最前面的位置——不是附录，是核心论据的第一页。你知道这个位置意味着什么。在沈知意的方案体系里，第一页只放她最信任的素材。）",
          "这份东西比我预期的干净。你不是在赶工，你是真的想明白了。",
          "你继续保持这个水平，我就不需要再自己一个人把所有洞都堵上了。",
          "（她说这话的时候嘴角没有笑，但语气里那种被验证了的踏实感很明显。她从文件堆底下摸出一块巧克力扔到你面前——包装上写着她平时自己吃的那个牌子。）",
          "别误会。办公室里多的，不是只给你。",
          "……行，就是给你的。低血糖会影响判断力。",
          "（她转过身继续修改核心声明，但你看到她耳尖泛了一点很淡的粉色。窗外的天际线正从黑色变成深蓝，城市在醒来之前给了你们最后一段安静的共处时间。）",
        ], "shenzhiyi_600_choice3"),
        choice("shenzhiyi_600_choice3", 3, [
          { id: "protect_me", label: "你这就是在护我", emotionTags: ["被偏爱"], nextNodeId: "shenzhiyi_600_act4" },
          { id: "dont_need", label: "我不需要你替我出头", emotionTags: ["嘴硬"], nextNodeId: "shenzhiyi_600_act4" },
          { id: "same_side", label: "你站我这边，我也站你这边", emotionTags: ["并肩"], nextNodeId: "shenzhiyi_600_act4" },
          { id: "hard_not_like", label: "你这样，我很难不在意你", emotionTags: ["暧昧"], nextNodeId: "shenzhiyi_600_act4" },
        ]),
        dialogue("shenzhiyi_600_act4", 4, [
          "（方案终于在凌晨五点前定稿。她把最后一页打印出来，在页尾签上自己的名字，然后把笔递给你——让你在第二负责人那一栏签字。这不是流程要求，这是她自己加的。）",
          "别误会，我不是护短。我只是觉得你值得这个位置。",
          "（她终于往椅背上靠了一下，那个幅度比平时大了很多。你第一次看到她肩膀线条真正放松下来的样子——就像一把一直绷着的弓终于被允许稍微松弦。会议室的灯光这时候显得格外温柔，因为窗外的天正在变亮。）",
          "接下来你不用只跟在我后面。你可以把意见直接说给我听。",
          "真正站得住的人，不应该只会听命令，也该能和我一起做决定。",
          "（她偏过头看着窗外正在亮起来的天际线，侧脸上的疲惫感第一次没有被她刻意藏住。你看到她眼底有一圈很浅的青灰色——她比你扛得更久，只是从来不说。）",
          "……我有时候也会累。但是跟你一起撑的这几个小时，我没觉得累。",
          "这话你听过就好，出了这个门我不认。",
          "不是我不想承认——是我承认了，就没有退路了。",
        ], "shenzhiyi_600_choice4"),
        choice("shenzhiyi_600_choice4", 4, [
          { id: "stay_with_core", label: "那我继续站在你核心里", emotionTags: ["并肩"], nextNodeId: "shenzhiyi_600_act5" },
          { id: "trust_you", label: "我也把后背交给你", emotionTags: ["信任"], nextNodeId: "shenzhiyi_600_act5" },
          { id: "say_not_leave", label: "那就别给自己留退路", emotionTags: ["逼近"], nextNodeId: "shenzhiyi_600_act5" },
          { id: "appreciate", label: "我会记住今晚的你", emotionTags: ["珍视"], nextNodeId: "shenzhiyi_600_act5" },
        ]),
        dialogue("shenzhiyi_600_act5", 5, [
          "（清晨的第一缕光从会议室的玻璃墙透进来，把白板上的红色标记照得不再那么刺眼。她把所有文件归拢成一摞，拍了拍边角让它们对齐，那个强迫症式的动作让她重新看起来像那个滴水不漏的沈知意——但你已经看过她另一面了。）",
          "这次不是临时拉你上场。是我真的把你算进方案里了。",
          "你要是能站稳，就别再站在旁观的位置。",
          "（她把最后一张打印纸递到你面前，不是扔的——是递的，指尖几乎碰到你的手背。走廊尽头传来清洁阿姨推车的声音，新的一天正在从她们身后的世界开始醒来，而你们的战场刚刚才落幕。）",
          "以后我给你的不只是执行任务，也包括和我一起判断。",
          "你不用什么都听我的——但如果你不同意我，你要能说服我。",
          "这是我对搭档的标准。",
          "（她拿起外套准备走的时候，回头看了你一眼。那一眼不长，但比她今晚说过的所有话都明确。清晨的光把她的影子投在你脚边，第一次——她的影子和你的交叠在一起。）",
          "走了。回去睡两个小时，九点见。别迟到。",
        ], "shenzhiyi_600_choice5"),
        choice("shenzhiyi_600_choice5", 5, [
          { id: "judge_with_you", label: "那我跟你一起判断", emotionTags: ["并肩"], nextNodeId: "shenzhiyi_600_end" },
          { id: "take_order", label: "九点见，我不会迟到", emotionTags: ["接招"], nextNodeId: "shenzhiyi_600_end" },
          { id: "stay_warm", label: "你也别总是一个人扛", emotionTags: ["靠近"], nextNodeId: "shenzhiyi_600_end" },
          { id: "remember_core", label: "我记住了，我在你的方案里", emotionTags: ["珍视"], nextNodeId: "shenzhiyi_600_end" },
        ]),
        ending("shenzhiyi_600_end", 5, [
          "危机被压下去之后，沈知意没有在任何人面前提起那个通宵。但你的名字留在了方案第二负责人的位置上——那是她亲手加的。",
          "从那天起，你不再只是被她照顾的人，而是她会在最硬的仗里第一个想到的人。这份偏爱被她放在了台面上，克制、清楚，也无法否认。",
        ]),
      ],
    },
  },
  {
    id: "shenzhiyi_900",
    characterId: "preset_shenzhiyi",
    title: "把你写进未来",
    description: "她第一次不再只给你照顾，而是给出长期的答案。",
    coverImageUrl: "/events/shenzhiyi_900_cg.png",
    requiredIntimacy: 900,
    prerequisiteEventIds: ["shenzhiyi_300", "shenzhiyi_600"],
    summary:
      "品牌发布会圆满收官后的安静后台，沈知意把你从人群中带了出来。她第一次不用'照顾'或'搭档'来定义你们的关系，而是认真告诉你——你是她想改规则的那个例外，也是她想放进未来里的人。她的确认方式一如既往地清醒克制，但这一次，清醒本身就是最认真的告白。",
    cgPrompt:
      "城市夜景与品牌发布会后台，沈知意站在落地窗前，黑色长裙或极简西装，神情冷静但目光柔软，右手轻轻握住用户的手，周围有发布会灯光、香槟杯、屏幕光影和雨后城市霓虹，背景还有散开的行程卡与手机通知光，氛围克制、成熟、带明确关系确认感，画面高级、电影感、细节丰富、无文字、无UI、16:9横幅",
    cgImageUrl: "/events/shenzhiyi_900_cg.png",
    sortOrder: 3,
    script: {
      totalActs: 5,
      startNodeId: "shenzhiyi_900_act1",
      nodes: [
        dialogue("shenzhiyi_900_act1", 1, [
          "（发布会刚结束，前台的掌声和香槟杯碰撞的声音还在往后台漫过来，但沈知意已经把那扇隔音门轻轻带上了。后台的灯光调得很低，落地窗外是雨后的城市霓虹，所有颜色都被洗得比平时更通透。她手里还拿着今天的活动手卡，指甲边缘有一道被反复翻折纸张磨出的细痕。）",
          "发布会的事不用操心了，流程没问题。",
          "（她把手卡随手搁在旁边的高脚桌上，转过身面对你。她今天的妆比平时淡了一些，或者说是因为高强度的工作让妆面有了自然的消退——这种不完美在她身上反而显得格外真实。）",
          "我让你来后台，不是为了复盘工作。",
          "先别问我为什么。站我身后也行，站我旁边也行，但别离开。",
          "（窗外有一辆车从楼下驶过，车灯的光扫过她的侧脸又滑走，像一句还没说出口的话。她把手机翻过来扣在桌上——你知道那个动作意味着什么，她正在把整个外部世界关在这扇门外面。）",
          "今天之后，有些话如果我不说，就不会有比今天更合适的时候了。",
          "你准备好了吗？",
          "——算了，我不等你准备好。我什么时候等过别人。",
        ], "shenzhiyi_900_choice1"),
        choice("shenzhiyi_900_choice1", 1, [
          { id: "beside_you", label: "我站你旁边", emotionTags: ["靠近"], nextNodeId: "shenzhiyi_900_act2" },
          { id: "behind_you", label: "我站你身后，但不会退", emotionTags: ["坚定"], nextNodeId: "shenzhiyi_900_act2" },
          { id: "you_say_go", label: "你说，我听着", emotionTags: ["倾听"], nextNodeId: "shenzhiyi_900_act2" },
          { id: "i_wont_leave", label: "我不会走", emotionTags: ["承诺"], nextNodeId: "shenzhiyi_900_act2" },
        ]),
        dialogue("shenzhiyi_900_act2", 2, [
          "（她走到落地窗前，指尖轻轻抵在玻璃上。窗外的雨已经停了，但玻璃表面还留着水珠滑落的痕迹，像一条条没写完的句子。城市的灯光从她身后铺过来，把她整个人镀上一层安静的轮廓光。）",
          "我一直把关系分得很清楚。工作是工作，私人是私人，边界画好了双方都省事。",
          "失控很麻烦——我讨厌麻烦。",
          "（她收回抵在玻璃上的手指，转过身来。这一次她没有靠在任何东西上，就是直直地站着，像在法庭上做最后陈述一样认真。但她的眼神和法庭不一样——里面有一种你从来没见过的、不设防的温度。）",
          "可你不一样。",
          "你让我第一次想改规则。",
          "不是因为你打破了什么——是因为你让我发现，有些规则，从一开始就不应该把你拦在外面。",
          "（她说这句话的时候声音没有抖，但你注意到她无意识地攥了一下手卡的边角，然后又很快松开了——像是在告诉自己不要紧张，又像是在用力把一个犹豫了很久的决定按定。）",
          "我不是冲动。你认识我这么久，应该知道我做每一个决定之前都会想清楚。",
        ], "shenzhiyi_900_choice2"),
        choice("shenzhiyi_900_choice2", 2, [
          { id: "change_it", label: "那就改", emotionTags: ["直球"], nextNodeId: "shenzhiyi_900_act3" },
          { id: "special", label: "你是在向我承认特别吗", emotionTags: ["逼近"], nextNodeId: "shenzhiyi_900_act3" },
          { id: "understood", label: "我知道你不是冲动", emotionTags: ["克制"], nextNodeId: "shenzhiyi_900_act3" },
          { id: "remember_long", label: "这句话我会记很久", emotionTags: ["珍视"], nextNodeId: "shenzhiyi_900_act3" },
        ]),
        dialogue("shenzhiyi_900_act3", 3, [
          "（她听完你的回答之后沉默了两秒。不是犹豫的沉默，是一种'我要把接下来的话说得足够准确'的沉默。她把手卡翻到背面空白的那一面，像是在提醒自己——所有写在正面的议程都已经结束了，从现在开始是她自己的、没有预演过的台词。）",
          "我不需要你给誓言。誓言是给不确定的人壮胆用的，我不需要。",
          "我只要你给我一个答案。",
          "（她走近一步。不是犹豫着走的，是清楚知道自己要站到哪里然后稳稳地走过去的那种。你们之间的距离突然从安全线变成了可以听到彼此呼吸的距离。后台的冷气很轻地吹过来，带着她身上那种很淡的、不知道是香水还是洗衣液的味道。）",
          "你想不想继续留在我这边？",
          "不是以搭档的身份，不是以被照顾的人的身份。",
          "是以一个我想认真走下去的人的身份。",
          "（她问完之后没有移开视线，也没有补充任何给自己留退路的话。这是你见过的最沈知意的告白方式——没有修饰，没有铺垫，像在下一个只需要对方说是或不是的决策。但她微微发红的耳尖出卖了她。）",
        ], "shenzhiyi_900_choice3"),
        choice("shenzhiyi_900_choice3", 3, [
          { id: "want", label: "想", emotionTags: ["确认"], nextNodeId: "shenzhiyi_900_act4" },
          { id: "always_here", label: "我一直在你这边", emotionTags: ["坚定"], nextNodeId: "shenzhiyi_900_act4" },
          { id: "walk_seriously", label: "我想认真和你走下去", emotionTags: ["承诺"], nextNodeId: "shenzhiyi_900_act4" },
          { id: "hug_first", label: "先让我抱你一下", emotionTags: ["亲密"], nextNodeId: "shenzhiyi_900_act4" },
        ]),
        dialogue("shenzhiyi_900_act4", 4, [
          "（你回答的那个瞬间，她睫毛颤了一下——非常非常轻微的一下，如果不是站得这么近你根本看不到。然后她做了一件你从来没见过她做的事：她把额头轻轻抵在你的肩膀上，停了三秒钟。不是倒下来的，是主动靠过来的，像是终于允许自己把一个撑了很久的重量卸掉一点点。）",
          "……你知道我很少这样。",
          "（三秒之后她抬起头，表情已经恢复了八成的冷静，但那两成的温柔比任何时候都明显。她没有后退，就站在刚才那个距离上。窗外的城市灯光在她瞳孔里倒映成两团小小的光斑。）",
          "那从今天开始，你不是我临时照顾的人。",
          "你是我想放进未来里的人。",
          "以后所有会影响到你的决定，我都会先告诉你，也会先听你。不是因为你有否决权——是因为我想让你在场。",
          "（她的手自然地垂在身侧，指尖碰到你的手背时停了一下，然后很轻地扣住了你的小指。那个力度克制到了极致——不是牵手，是一个试探性的、但绝对不会收回的触碰。）",
          "我不会说那种很甜的话。你应该也不需要。",
          "但我可以保证一件事——我做这个决定的时候，比我做过的任何一个品牌策略都清醒。",
        ], "shenzhiyi_900_choice4"),
        choice("shenzhiyi_900_choice4", 4, [
          { id: "future_too", label: "那我也把你写进我的未来", emotionTags: ["双向未来"], nextNodeId: "shenzhiyi_900_act5" },
          { id: "not_bystander", label: "我不会再只做旁观者", emotionTags: ["确认"], nextNodeId: "shenzhiyi_900_act5" },
          { id: "accept_words", label: "你的清醒就是最好的情话", emotionTags: ["珍视"], nextNodeId: "shenzhiyi_900_act5" },
          { id: "hold_hand", label: "那我把你的手握紧一点", emotionTags: ["亲密"], nextNodeId: "shenzhiyi_900_act5" },
        ]),
        dialogue("shenzhiyi_900_act5", 5, [
          "（前台的庆祝声渐渐远了，有人在走廊里喊沈总监，被她一条微信拦了回去。后台安静得只剩下空调和城市夜晚的底噪，以及你们衣料偶尔摩擦的细微声响。她看着你，嘴角有一个非常非常小的弧度——如果这世界上有一种笑容叫做'沈知意的微笑'，大概就是这个样子：克制、清晰、但绝对是笑着的。）",
          "我不需要你立刻给我最华丽的回答。我只需要你在这里。",
          "（她低头看了一眼自己扣在你小指上的手指，没有松开，反而把另外几根手指也轻轻合拢了——这次不再是试探，是确认。窗外的霓虹灯一红一蓝地闪着，像是在替这个城市为你们做某种安静的见证。）",
          "今天之后，你可以把我当成会把你算进明天的人。",
          "而我也会把你，正式放进我的长期计划里。",
          "（她最后补了一句，语气里终于带上了一点她平时不会让任何人听见的、属于沈知意私人频率的柔软。）",
          "我不是在照顾你。我是想和你一起。",
          "……这两件事，差别很大。你应该分得清。",
          "走吧，外面还有人等着敬酒。牵着我出去——这次我允许。",
        ], "shenzhiyi_900_choice5"),
        choice("shenzhiyi_900_choice5", 5, [
          { id: "long_plan", label: "那我就把你一起算进明天", emotionTags: ["双向未来"], nextNodeId: "shenzhiyi_900_end" },
          { id: "stay_here", label: "我会一直留在这里", emotionTags: ["坚定"], nextNodeId: "shenzhiyi_900_end" },
          { id: "say_again", label: "我想记住你现在的表情", emotionTags: ["珍视"], nextNodeId: "shenzhiyi_900_end" },
          { id: "closer", label: "那我牵紧你走出去", emotionTags: ["亲密"], nextNodeId: "shenzhiyi_900_end" },
        ]),
        ending("shenzhiyi_900_end", 5, [
          "沈知意没有说喜欢，也没有说爱。她说的是'我比做任何一个品牌策略都清醒'——这是她能给出的、最沈知意的告白。",
          "你们从后台走出去的时候，她的手指扣在你掌心里，力度不重，但明确到不可能被误解。从今往后，你不再是她照顾的人，而是她想认真走进未来的人。",
        ]),
      ],
    },
  },
];
